### ISSUE TITLE
No backwards compatibility + signing

### ISSUE THREAD

**Issue by Crusader2010** [HtmlTags/htmltags#104]
Hi,

I had to work on an older project that used version 4.2.0 of HtmlTags and, after upgrading to the latest version, an error popped up that there is no method "ToPrettyString()".

What happened to it? If it was replaced by a new one, why wasn't the backward compatibility kept (i.e. replace the code for ToPrettyString() to actually call your new method) ?

Also, is it possible to sign this package? I'm getting a null publicKeyToken and I need to force a binding redirect because of the above issue.

**Comment by jbogard** [comment]
Can you open a separate issue for signing?

And for the ToPrettyString part - I wanted to keep it, but I couldn't
figure out how to make it work :(

**Comment by Crusader2010** [comment]
Let me know if I can help with that. First I need to understand what changed between the version that had ToPrettyString() and the first version that didn't. Do we have access to the code (for both of those versions)?

**Comment by jbogard** [comment]
Yeah the original version is just in the history before ASP.NET Core.
