### ISSUE TITLE
Target .NET Standard (without ASP.NET dependencies)

### ISSUE THREAD

**Issue by leus** [HtmlTags/htmltags#105]
To use HtmlTags in a .NET Core application we are forced to add a lots of ASPNET.Core dependencies which aren't needed.

Please add a NuGet package that targets NET Standard separated from ASPNET.Core dependencies.

**Comment by jbogard** [comment]
I'm not sure how to do this - I have to make `HtmlTag` implement `IHtmlContent` to allow the rendering to happen.

**Comment by jbogard** [comment]
If you have ideas on how to make this work, I'll be happy to entertain them.

**Comment by leus** [comment]
I managed creating a netstandard class library by adding `Microsoft.AspNetCore.Html.Abstractions` and `Newtonsoft.Json` (a newer version, because the old one added too many dependencies). I don't know your policy on nuget dependencies (update and consolidate everything? keep old versions?)

**Comment by jbogard** [comment]
Just send a PR and lemme see from there!

**Comment by jbogard** [comment]
Or if not a PR, point me to a repo where you did this so I can compare.

**Comment by jbogard** [comment]
So I think the way forward on this is to convert the existing HtmlTags package to just a library, and have the `HtmlTags.AspNetCore` one reference it. This might involve then moving it out to a separate repo.

Then I'd drop classic ASP.NET support.

What are your thoughts on using the new System.Text.Json stuff and dropping Newtonsoft.Json?

**Comment by leus** [comment]
That was my initial plan, but got caught in some details with newer versions and testing (`DataAnnotationsModelValidatorProvider` and `DefaultValidatorObject` are now internal, and I didn't went too far looking for that). I've just added a simple project for now, but I can give it a try again.

Newer versions of Newtonsoft.Json are quite cheap to use with the latest core versions (very few dependencies) but I'd love to give it a try, just because it seems like the right thing to do.

**Comment by leus** [comment]
Here's a PR: https://github.com/HtmlTags/htmltags/pull/109

**Comment by jbogard** [comment]
I just released a version (8.0.0) that only targets `netstandard2.0` and `netcoreapp3.0`.

**Comment by TheConservativeCoder** [comment]
Since the update to version 8.0.0 it has brought in lots of Asp.Net Core assemblies in to my .Net Framework MVC web app and causes it fail on razor views whenever htmltags is used.

![image](https://user-images.githubusercontent.com/264872/66903160-dcb11a00-eff9-11e9-8539-056e4736aa64.png)

**Comment by jbogard** [comment]
I'm still writing up release notes, but the latest version only targets ASP.NET Core. 7.x will be the last version to target legacy ASP.NET.
