### ISSUE TITLE
AppendText always puts text before any elements

### ISSUE THREAD

**Issue by zach27** [HtmlTags/htmltags#114]
When adding content to an element, it seems that `AppendText()` always puts the text before other elements, regardless of the order you append them. I would expect any append method to generate the content in the order you append.

## Example

```csharp
var span = new HtmlTag("span")
    .Text("NOTE: ");

var paragraph = new HtmlTag("p")
    .Append(span)
    .AppendText("Please read before continuing");

Console.WriteLine(paragraph.ToString());
```

### Expected output:

```html
<p><span>NOTE: </span>Please read before continuing</p>
```

### Actual output:
The text is prepended before the `span`:

```html
<p>Please read before continuing<span>NOTE: </span></p>
```

The library seems to assume an element will either have (1) text content or (2) one or more HTML elements, but not both. I know I could put the text inside another span, but this seems like unnecessary overhead. **How can I accomplish this without the overhead?**

**Comment by dharmatech** [comment]
Came here to report this same issue. :-)

Is this considered a bug?

**Comment by jbogard** [comment]
Yes :)

**Comment by jbogard** [comment]
I think the way we'll have to handle this is treat text as a kind of "tag" that can get appended. Versus now, we just set an `_innerText` value.
