### ISSUE TITLE
Cannot add Non-Breaking Space

### ISSUE THREAD

**Issue by tolsen64** [HtmlTags/htmltags#115]
Adding "`&nbsp;text&nbsp;`" to text is rendered as "`&nbsp;text&nbsp;`" instead of " text ".

**Comment by tgaertner-recom** [comment]
I found the extension method .AppendHtml("&nbsp;") is doing what you need.

For completeness your example translates to:
`.AppendHtml("&nbsp;text&nbsp;")`

Do not use this:
`.AppendHtml("&nbsp;").Text("text").AppendHtml("&nbsp;")`

because this renders in wrong order. (see #114)
