### ISSUE TITLE
New Release? Issues in SonarQube

### ISSUE THREAD

**Issue by paizsrita** [HtmlTags/htmltags#124]
Hello, 

We are using HtmlTags in two of our projects. I updated the framework version of one of these projects recently and since then SonarQube throws 27 vulnerabilities because of the dependencies of this package. I noticed that there have been some commits not so long ago so I was wondering if maybe there could be a new release in the near future?

Thanks in advance, 
Rita.

**Comment by jbogard** [comment]
Done!

And just FYI SonarQube is *awful* about framework dependencies. HtmlTags only has framework dependencies, which depend on what runtime you're running against. We just exclude this package from the scanning because it's all false positives.
