### ISSUE TITLE
Trying to use version 9.0.0 (from nuget) in linqpad fails

### ISSUE THREAD

**Issue by boggye** [HtmlTags/htmltags#125]
Hi,

I tried to play with this library in linqpad 7.7.15 targeting .net 6, and I get this error:

`Could not load file or assembly 'Microsoft.AspNetCore.Html.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

I noticed that the Microsoft.AspNetCore.Html.Abstractions is deprecated: https://www.nuget.org/packages/Microsoft.AspNetCore.Html.Abstractions. The last version available in Linqpad is 2.2.0.

What else do I need to do in order to be able to use HtmlTags?

Thank you

**Comment by boggye** [comment]
Never mind, my fault, I had to check a box 'reference Asp.Net Core' and it started working. All good, sorry for the noise.

**Comment by jbogard** [comment]
No worries! I release new versions with every LTS of .NET Core.
