### ISSUE TITLE
How to parse MVCHtmlString or String into HTML Tag

### ISSUE THREAD

**Issue by syed-afraz-ali** [HtmlTags/htmltags#65]
I am trying to use HtmlTags to write a wrapper around some MVC Extension methods. For this I need to generate a HtmlTag from MVCHtmlString and then add some attributes on top of it. In the current version, I cannot find a way to create a HtmlTag from String. 

Can you please guide me if it is possible and what is the right way to do it?

**Comment by jbogard** [comment]
You don't do this. You create MVCHtmlStrings from HtmlTags but not the
reverse. This is because one is just a string and the other is a rich
object. HtmlTags does not have any facility to parse arbitrary HTML into a
tag object.
