### ISSUE TITLE
Remove uses of profile - or clarify its purpose

### ISSUE THREAD

**Issue by ajepst** [HtmlTags/htmltags#69]
Profile appears to not be useful, and complicates the API. The two are also positionally switched in some method parameters so when reading one vs/the other it gets a little confusing. One can easily be confused for the other in usage as well. The project should either remove profile entirely, or clearly outline when and why profile should be used, if it does have a necessary purpose.

**Comment by jeremydmiller** [comment]
The *original* purpose of the profile was to be able to use Html conventions in different modes within the same app. At the time, we had one set of conventions for "New" entity pages where the conventions would write in simple editors, and an "Edit" mode where the conventions would write in "edit in place" controls.

**Comment by ajepst** [comment]
@jeremydmiller Thanks for the background. A little context for these issues-they are all things that caught our eye during a pairing session @jbogard and I did today, so I know he plans to check back on them and may add his own thoughts as well.

**Comment by jeremydmiller** [comment]
Not that it helps you in the slightest, but you're also using the raw model w/o the old HtmlConventionRegistry thing we used in FubuMVC to add a configuration FI on top of HtmlTags.
