### ISSUE TITLE
AspNetCore - Unable to select a TagBuilderPolicy for subject Profile: Default, Subject: HtmlTags.Conventions.ElementRequest

### ISSUE THREAD

**Issue by michael-wolfenden** [HtmlTags/htmltags#75]
I went to use HtmlTags in a new AspNetCore application and got the following exception:

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Unable to select a TagBuilderPolicy for subject Profile: Default, Subject: HtmlTags.Conventions.ElementRequest

Turns out the issue was my configuration

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddHtmlTags();
}
```

I had expected this to add the default registry, however it instead calls the overloaded `AddHtmlTags` method that accepts a `params` array with no registries

The solution was

```csharp
public void ConfigureServices(IServiceCollection services)
{
       ....
	services.AddHtmlTags((_) => {});
}
```

This was non obvious and tripped me up and I'm sure other people will hit the same issue.

The real fix would require changing the extension method signatures (a breaking change). 

Happy to send a pull request if you provide some direction.

Thoughts?

**Comment by jbogard** [comment]
Ah, so the assumption is you'd add *some* configuration. The out-of-the-box config will always need to be modified.
