### ISSUE TITLE
Inner Text Placement

### ISSUE THREAD

**Issue by ETFairfax** [HtmlTags/htmltags#76]
Unless I'm missing something (please let me know if I am), I am unable to specify where the inner text is placed in relation to any child elements.

I've tried `InsertFirst()`, but the Text still precedes the inserted tag.

I've never forked, branched, or pull requested a git hub project before;  I would have been happy to contribute to it but wasn't sure how!!  However, looking at the code I'm guessing that the following will do it. 

**Code**

I propose that a new PlaceTextAfterChildElements property is created in the `HtmlTag` class.....

```
/// <summary>
/// Setting this value to true will result in the _innerText being rendered after any child elements.
/// Setting this value to false will result in the _innerText being rendered before any child elements.
/// </summary>
public bool PlaceTextAfterChildElements { get; set; } = false;
```

..and modify WriteContent() to interrogate the new bool....

```
private void WriteContent(HtmlTextWriter html)
{

    if (PlaceTextAfterChildElements)
        _children.Each(x => x.WriteHtml(html));  // Render child elements BEFORE _innerText 

    if (_innerText != null)
    {
        if (_encodeInnerText)
        {
            html.WriteEncodedText(_innerText);
        }
        else
        {
            html.Write(_innerText);
        }
    }

    if (!PlaceTextAfterChildElements)
        _children.Each(x => x.WriteHtml(html)); // Render child elements AFTER _innerText 
}
```

**Unit test**

```
[Fact]
public void place_text_after_child_elements()
{
    var tag = new HtmlTag("div");
    tag.Text("Foo");
    tag.Append("span");
    tag.InsertFirst(new HtmlTag("p"));

    tag.PlaceTextAfterChildElements = true; 

    tag.ToString().ShouldEqual("<div><p></p><span></span>Foo</div>");
}
```

Cheers.

**Comment by jeremydmiller** [comment]
It’s annoying, but you can get around that by using a LiteralTag to wrap the inner text and inserting that first.

**Comment by ETFairfax** [comment]
Thank you Jeremy.  That's helped me get round the problem I face right now.
