### ISSUE TITLE
Using a html tag name that is not registered with HtmlTextWriter throws a KeyNotFoundException

### ISSUE THREAD

**Issue by benmrcit** [HtmlTags/htmltags#77]
I have a HtmlHelperExtension method that returns a html5 time tag.
 `<time datetime="2016-05-19T00:00:00">19 May 2016</time>`

This works up to and including version 3.0.0.186.

I just updated to version 4.1.0 and it starts throwing a KeyNotFoundException.

I am using AspNet.Mvc V5.2.3 on .Net 4.5.

In a quick unit test, these run with no problem:

```
new HtmlTag("li").ToHtmlString();
new HtmlTag("del").ToHtmlString();
new HtmlTag("i").ToHtmlString();
```

However these throw exceptions:

```
new HtmlTag("date").ToHtmlString();
new HtmlTag("time").ToHtmlString();
```

StackTrace:
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at HtmlTags.HtmlTextWriter.GetTagKey(String tagName)
       at HtmlTags.HtmlTextWriter.set_TagName(String value)
       at HtmlTags.HtmlTextWriter.RenderBeginTag(String tagName)
       at HtmlTags.HtmlTag.WriteBeginTag(HtmlTextWriter html)
       at HtmlTags.HtmlTag.WriteHtml(HtmlTextWriter html)
       at HtmlTags.HtmlTag.ToString(HtmlTextWriter html)
       at HtmlTags.HtmlTag.ToString()
       at HtmlTags.HtmlTag.ToHtmlString()

**Comment by besslwalker** [comment]
I'm also having this problem, in my case with semantic HTML5-specific elements such as header, section, etc. and media HTML5-specific elements such as audio and video.

I'm also using 4.1.0 on .NET 4.5.

**Comment by jeremydmiller** [comment]
I'm getting this too. @jbogard I can look into this problem tomorrow and give you a PR for it.

**Comment by mhov** [comment]
I got this trying to add "optgroup".

**Comment by andrewmurray** [comment]
I just started using HtmlTags yesterday and hit this problem today with the "nav" tag.

**Comment by FlukeFan** [comment]
Got this today; worked around it with this snippet:

`    public class HtmlTagRegister
    {
        private class TagRegister : HtmlTextWriter
        {
            private TagRegister() : base(null) { }

            public static void Register(string tagName)
            {
                RegisterTag(tagName, HtmlTextWriterTag.Unknown);
            }
        }

        public static void RegisterUnknownTag(string tagName)
        {
            TagRegister.Register(tagName);
        }
    }`

Then call from a static constructor for all the 'custom' tags required:

`    public class UtilityClass
    {
        static UtilityClass()
        {
            HtmlTagRegister.RegisterUnknownTag("nav");
            HtmlTagRegister.RegisterUnknownTag("canvas");
        }
    }
`

**Comment by cveld** [comment]
@FlukeFan I followed your guidance but I am still getting the exception. What am I doing wrong? Can you share the full `HtmlTextWriter` example?

**Comment by Prnda1976** [comment]
I'm having the same issue. I am a bit baffled as to why is this not listed somewhere under "breaking changes." Anyway, my answer for now is to revert back to version 3.0.0.1.

**Comment by jbogard** [comment]
Fixed now.
