### ISSUE TITLE
Referenced assembly 'HtmlTags' does not have a strong name

### ISSUE THREAD

**Issue by cveld** [HtmlTags/htmltags#78]
I try to build an assembly that referencs the HtmlTags assembly through the installation of the nuget package.

Now I am getting the following error:
` Error	6	Assembly generation failed -- Referenced assembly 'HtmlTags' does not have a strong name` 

The resulting assembly needs to be deployed towards the GAC.

**Comment by jbogard** [comment]
Use the StrongNamer package to fix this. This package is not strong named,
nor will ever be.
