### ISSUE TITLE
Fluent API for creating siblings

### ISSUE THREAD

**Issue by cveld** [HtmlTags/htmltags#79]
I am looking for the best way to code the creation of siblings with children.
Currently I have:
`var tag = new HtmlTag("h3");
tag2 = new HtmlTag("ul");
tag.After(tag2);
tag2.Add("li");
` 

But this is quite ugly. I was expecting that the following would work:
`tag.After("ul").Add("li");` 
Or something along these lines.

What would be your guidance?

**Comment by jeremydmiller** [comment]
@cveld, 

You can do tag.Add("ul/li") to add an <li> inside of a <ul>. You could also do tag.Add("ul").Add("li"). There's also an overload somewhere to use a nested closure to add and configure a child element in a single call so you don't lose the scope of the original parent.
