### ISSUE TITLE
Remove reference to System.Web

### ISSUE THREAD

**Issue by dario-l** [HtmlTags/htmltags#82]
Currently I'm working with NancyFx hosted in OWIN (without System.Web). I want to use HtmlTags but it requires reference to System.Web and I don't want to do it. Is it even possible to make HtmlTags working without that reference?

**Comment by jbogard** [comment]
I use System.Web for encoding in ASP.NET, and something else for ASP.NET
Core. I don't know what Nancy has in the way of HTML encoding.

When you reference the HtmlTag package, what errors are you seeing? I'm not
at all familiar with Nancy.

**Comment by jbogard** [comment]
So I removed the encoding piece in favor of the encoding package, but I still need IHtmlString. The .NET Core version is cleaner, though.
