### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by HamedFathi** [HtmlTags/htmltags#83]
Hi please support .NET Core and ASP.NET Core

**Comment by jbogard** [comment]
I do, with https://www.nuget.org/packages/HtmlTags.AspNetCore/

**Comment by jbogard** [comment]
I updated the readme to include these instructions.

**Comment by jbogard** [comment]
A plain .NET Core app? I target netstandard2.0, what else are you looking for?

**Comment by leus** [comment]
Just not to have the whole ASPNET.Core dependency chain.

**Comment by jbogard** [comment]
Can you open a new issue? That’s a different concern altogether.
