### ISSUE TITLE
Editors don't honour [DisplayFormatAttribute] DataFormatString

### ISSUE THREAD

**Issue by jimmcslim** [HtmlTags/htmltags#84]
It looks like when generating editors/inputs that any `DisplayFormatAttribute` applied to the property doesn't impact the value that the text of the input is set to, if the attribute's `ApplyFormatInEditMode` property is set to true.

I think I can add this behaviour myself via an `IElementModifier` implementation, but is it the sort of thing that the library should do by default (or is it out of scope?)

**Comment by jbogard** [comment]
pull request?

**Comment by jimmcslim** [comment]
Would an `IElementModifier` implementation suffice, as HtmlTags.Utils of sorts?, as I now have a working one of those already!

The implementation of `Matches(ElementRequest token)` would check that the property in question is decorated with `[DisplayFormat]` and the underlying type implements `IFormattable`.
