### ISSUE TITLE
href="#name" doesn't work

### ISSUE THREAD

**Issue by FahaoTang** [HtmlTags/htmltags#88]
Hi,
As mentioned when writing with AddAttribute, char '#' is always escaped to '%23'. 
And I had to use the following approach to implement, which is not very elegant:

```
writer.Write("<a ");
writer.WriteAttribute("href", "#" + method.Value.Name, false);
writer.Write($">{method.Value.Name}</a>");
```

**Comment by jbogard** [comment]
Yikes well that's ugly.

**Comment by jbogard** [comment]
I couldn't reproduce, see the test I added.
