### ISSUE TITLE
Upgrade to version 6 from a .net 4.6.2 error

### ISSUE THREAD

**Issue by laitang2000** [HtmlTags/htmltags#90]
Just upgraded to version 6 from 5.0.2 and I get this error

`Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

**Comment by jbogard** [comment]
I usually see that when the NuGet client version is old. Do you have any other details? What .NET version? NuGet client version? Have you tried uninstalling it and reinstalling it?
