### ISSUE TITLE
Localization Supported?

### ISSUE THREAD

**Issue by andrewjknox** [HtmlTags/htmltags#91]
Does the library support localization in ASP.NET Core? Labels for example don't seem to pull through data annotations but falling back to Html.LabelFor will pull the localized value in from a resource file.

Using a custom label builder where I'm able to do this, just checking I hadn't missed something!

**Comment by jbogard** [comment]
Nope, but I take pull requests :)

**Comment by jbogard** [comment]
I'm planning to add data annotations support in the next release.
