### ISSUE TITLE
Text / value overrides not working after upgrade to 7.0.0

### ISSUE THREAD

**Issue by mycroes** [HtmlTags/htmltags#95]
After upgrading HtmlTags to 7.0.0 my conventions are no longer working as expected. 

Sample:
```csharp
Editors.IfPropertyIs<DateTimeOffset>().AddClass("bla");
Editors.IfPropertyIs<DateTimeOffset>().ModifyWith(m =>
                m.CurrentTag.Attr("type", "datetime-local")
                    .Value(m.Value<DateTimeOffset?>()?.ToLocalTime().DateTime.ToString("yyyy-MM-ddTHH:mm")));
```

This will properly add the class 'bla' and the type will be 'datetime-local', but the value will still be set using the default `DateTimeOffset.ToString()` format (I.e.: yyyy-MM-dd HH:mm:ss Z or something).

The same is true for:
```csharp
Displays.IfPropertyIs<DateTimeOffset>().BuildBy<DateTimeBuilder>();

// DateTimeBuilder : IElementBuilder
private HtmlTag RenderTag(DateTime? dateTime)
{
    var text = dateTime == null ? "-" : GetDateTimeText(dateTime.Value);
    return new HtmlTag("span").Text(text).Title(dateTime?.ToString("g")).Data("toggle", "tooltip");
}
```
Here I get a span with title and data-toggle tooltip, but the text is overriden with default `DateTimeOffset.ToString()` (for a property of type `DateTimeOffset`).

You can find the full conventions used at https://github.com/mycroes/SupportManager/blob/package-update/SupportManager.Web/Infrastructure/Tags/DefaultAspNetMvcHtmlConventions.cs .

All of this did work with HtmlTags 6.0.0, but I can't find any probable cause. I also tried omitting the defaults (by building a `HtmlConventionLibrary` around my `HtmlConventionRegistry`), but when combining that with `Displays.Always.BuildBy<SpanDisplayBuilder>();` I still get the same result.

**Comment by mycroes** [comment]
Cause for the problem is `ModelMetadataTagExtensions.ModelMetadata(...)` which was adding default modifiers after modifiers from consumer `HtmlConventionRegistry`-s. Because of this the default `Text` for `Displays` and default `Value` for `Editors` would always be applied as final modifier, preventing customization of those properties using `ModifyWith(...)`.

**Comment by jbogard** [comment]
Ah OK, so I shouldn't use modifiers it seems.

**Comment by mycroes** [comment]
I will test this, but I thought there were other issues when only swapping the registration order.

**Comment by jbogard** [comment]
I got your repro to pass at least

**Comment by jbogard** [comment]
Yes, there were other issues it turns out. I tried it out on a project, and it got messed up. I have to register the extensions as:

 - Modifiers
 - Naming convention
 - Your extensions
 - Builders

Builders are a "first one to match, wins", so the defaults need to go last. I'm pushing out a 7.0.2 release to fix this and unlist the others.

**Comment by mycroes** [comment]
Thanks for testing and fixing!
