### ISSUE TITLE
7.0.2 breaks editor dot notation convention

### ISSUE THREAD

**Issue by markgould** [HtmlTags/htmltags#98]
Not quite sure what caused this yet, but upgrading from 7.0.x to 7.0.2 breaks the dot notation when using a setup like this: https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/blob/master/ContosoUniversity/Infrastructure/Tags/TagConventions.cs

For example in 7.0.2 a field named Description gets a name of DataDescription and an id of DataDescription. After reverting to 7.0.1 it is named Data.Description and Data_Description respectively.

**Comment by jbogard** [comment]
Siiiiiiiigh

**Comment by WadeTheFade** [comment]
Just double checking, but I think @jbogard fixed this in 7.0.3?
https://github.com/HtmlTags/htmltags/commit/5ecbedec1beeeecc7d97af8467af6b017cfd5dc3

**Comment by jbogard** [comment]
Yep!
