### ISSUE TITLE
Usage of .Text() in custom builder always gets overridden

### ISSUE THREAD

**Issue by mycroes** [HtmlTags/htmltags#99]
This is related to #95 (and a regression since HtmlTags 6.x). When creating a custom builder as following:
```csharp
public class DateTimeBuilder : IElementBuilder
{
    public static string Token = "date-time-builder";

    public HtmlTag Build(ElementRequest request)
    {
        return new HtmlTag("span").Text(Token);
    }
}
```
the test below fails:
```csharp
[Fact]
public void ShouldAllowOverridingOfConventionTextUsingCustomBuilder()
{
    var offset = new DateTimeOffset(2018, 1, 1, 12, 00, 00, TimeSpan.FromHours(-6));
    var subject = new Subject {DateValue = offset};
    var helper = GetHtmlHelper(subject);

    var display = helper.Display(m => m.DateValue);

    display.Text().ShouldBe(DateTimeBuilder.Token);
}
```

I'd love to know if you intend to fix this or if you'll accept this as expected behavior (I guess a modifier can still be used to override the text).

**Comment by jbogard** [comment]
Do you have a larger example? What does your registration code look like?

**Comment by mycroes** [comment]
Provided as pull request. I guess the test can't be more to the point (and for this issue I don't see any use for additional configuration), but the code is part of [mycroes/SupportManager](/mycroes/SupportManager) ([...Conventions.cs](/mycroes/SupportManager/blob/master/SupportManager.Web/Infrastructure/Tags/DefaultAspNetMvcHtmlConventions.cs)).

**Comment by mycroes** [comment]
Well actually, the issue is part of SupportManager, where I use a builder to properly format DateTime(Offset)s, the code is just a contrived test.

**Comment by jbogard** [comment]
Finally coming back to this. This is because the ModelMetadata extensions (that make these behave like ASP.NET Core) are modifiers, not builders. Builders go first, then modifiers. You've replaced the builder, not the modifier.

Adding your modifier makes this work:

```csharp
reg.Displays.IfPropertyIs<DateTimeOffset>().ModifyWith(m => m.CurrentTag.Text("date-time-builder"))
```
